### Test User Signup
POST https://backend-mit.onrender.com/api/users/signup
Content-Type: application/json

{
  "email": "shiny@example.com",
  "username": "shinyShai",
  "password": "123456"
}


###
POST https://backend-mit.onrender.com/api/users/login
Content-Type: application/json

{
  "email": "shiny@example.com",
  "password": "123456"
}



###
POST https://backend-mit.onrender.com/api/users/create
Content-Type: application/json

{
  "title": "Hidden Waterfall",
  "location": "Mountain Province",
  "description": "A newly found waterfall surrounded by mossy rocks.",
  "tangibility": "Natural",
  "user": "shinyshai", 
  "userId": "68c81a82f47fa2a6c0fa0f70"
}

